EMOJI_REGEX = r'^<a?:[a-zA-Z0-9_]+:([0-9]+)>$'

WASTEBASKET = "\N{WASTEBASKET}"
WHITE_CHECK_MARK = "\N{WHITE HEAVY CHECK MARK}"
ARROWS_COUNTERCLOCKWISE = "\N{ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCLE ARROWS}"
RECYCLING = "\N{BLACK UNIVERSAL RECYCLING SYMBOL}"
CROSS_MARK = "\N{CROSS MARK}"
